## Creating a Pandas Series with a List

In [1]:
import pandas as pd

In [2]:
pd.Series([10, 20, 30, 40, 50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
list_data = [2, 4, 6, 8, 10]
list_index = ["a", "b", "c", "d", "e"]

In [4]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

In [5]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [6]:
type(variable)

pandas.core.series.Series

In [7]:
list_data = [2, 4, 6, 8, 10, 12]
list_index = ["a", "b", "c", "d", "e"]

In [8]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

ValueError: Length of values (6) does not match length of index (5)

## Creating a Pandas Series with a Dictionary

In [ ]:
import pandas as pd 

In [ ]:
dictionary = {"ferrari" : 334.7, "porche" : 337.9, "lamborghini" : 349}

In [ ]:
pd.Series(data = dictionary)

In [ ]:
variable = pd.Series(data = dictionary, index = ["porche", "bugatti", "ferrari"])

In [ ]:
variable

## Creating Pandas Series with NumPy Array

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
example = np.array([1, 3.3, 5, 7.2, 9])
labels = np.array(["a", "b", "c", "d", "e"])

In [ ]:
variable = pd.Series(data = example, index = labels)

In [ ]:
variable

## Object Types in Series

In [ ]:
import pandas as pd

In [ ]:
pd.Series(["world", 100, 5.8, False])

In [ ]:
example = pd.Series(["world", 100, 5.8, False])

In [ ]:
example[0]

In [ ]:
print(type(example[0]))

In [ ]:
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

In [ ]:
pd.Series([sum, type, max])

## Examining the Primary Features of the Pandas Series  

In [ ]:
import pandas as pd

In [ ]:
example = pd.Series([10, 20, 30, 40, 50, 60, 70])

In [ ]:
example

In [ ]:
example.axes

In [9]:
example.dtype

NameError: name 'example' is not defined

In [10]:
example.size

NameError: name 'example' is not defined

In [11]:
example.ndim

NameError: name 'example' is not defined

In [12]:
example.head()

NameError: name 'example' is not defined

In [13]:
example.tail()

NameError: name 'example' is not defined

## Most Applied Methods on Pandas Series

In [14]:
import pandas as pd

In [15]:
variable = pd.Series([8, 3, 6, 5, 1], index = ["b", "d", "c", "a", "e"])

In [16]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [17]:
new_variable = variable.sort_index()

In [18]:
new_variable

a    5
b    8
c    6
d    3
e    1
dtype: int64

In [19]:
new_variable2 = variable.sort_values()

In [20]:
new_variable2

e    1
d    3
a    5
c    6
b    8
dtype: int64

In [21]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [22]:
variable.isin([6, 1])

b    False
d    False
c     True
a    False
e     True
dtype: bool

In [23]:
variable[variable.isin([6, 1])]

c    6
e    1
dtype: int64

In [24]:
variable.values

array([8, 3, 6, 5, 1], dtype=int64)

In [25]:
[i for i in variable.values]

[8, 3, 6, 5, 1]

In [26]:
variable.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [27]:
[i for i in variable.index]

['b', 'd', 'c', 'a', 'e']

In [28]:
variable.items

<bound method Series.items of b    8
d    3
c    6
a    5
e    1
dtype: int64>

In [29]:
variable.items()

In [30]:
list(variable.items())

[('b', 8), ('d', 3), ('c', 6), ('a', 5), ('e', 1)]

In [31]:
for index, value in variable.items():
    print(index, "-", value)

b - 8
d - 3
c - 6
a - 5
e - 1


## Indexing and Slicing Pandas Series

In [32]:
import pandas as pd

In [33]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [34]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [35]:
example["Germany"]

'+49'

In [36]:
example[1]

'+49'

In [37]:
example["France":"Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [38]:
example[2:5]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [39]:
example[2:5:2]

France    +33
Sweden    +46
dtype: object

In [40]:
example[["Norway", "Turkey"]]

Norway    +47
Turkey    +90
dtype: object

## Creating Pandas DataFrame with List

In [41]:
import pandas as pd

In [42]:
list_example = [5, 10, 15, 20, 25]

In [43]:
list_example

[5, 10, 15, 20, 25]

In [44]:
pd.DataFrame(data = list_example, columns = ["values"], dtype = "float" )

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

## Creating Pandas DataFrame with NumPy Array

In [45]:
import numpy as np
import pandas as pd

In [46]:
array_example = np.random.randint(0, 50, (4, 4))

In [47]:
array_example

array([[ 8, 49, 11, 30],
       [24, 24, 20,  3],
       [ 2, 16, 21, 33],
       [ 2,  8, 43, 20]])

In [48]:
df = pd.DataFrame(array_example, index = ["a", "b", "c", "d"], columns = ["val1", "val2", "val3", "val4"])

In [49]:
df

val1  val2  val3  val4
a     8    49    11    30
b    24    24    20     3
c     2    16    21    33
d     2     8    43    20

## Creating Pandas DataFrame with Dictionary

In [50]:
import numpy as np
import pandas as pd

In [51]:
x = np.random.randint(10, 50, size = 6)

In [52]:
x

array([19, 47, 48, 24, 26, 30])

In [53]:
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

In [54]:
dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

In [55]:
dict_example

{'val1': array([19, 47, 48, 24, 26, 30]),
 'val2': array([39, 46, 16, 43, 35, 13]),
 'val3': array([18, 49, 31, 45, 19, 37]),
 'val4': array([17, 27, 49, 42, 44, 32])}

In [56]:
df = pd.DataFrame(dict_example)

In [57]:
df

val1  val2  val3  val4
0    19    39    18    17
1    47    46    49    27
2    48    16    31    49
3    24    43    45    42
4    26    35    19    44
5    30    13    37    32

## Examining the Properties of Pandas DataFrames

In [58]:
import numpy as np
import pandas as pd

In [59]:
x = np.random.randint(10, 50, size = 6)
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

df = pd.DataFrame(dict_example)

In [60]:
df

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [61]:
df.head()

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28

In [62]:
df.head(3)

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30

In [63]:
df.tail(3)

val1  val2  val3  val4
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [64]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [65]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [66]:
df

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [67]:
df.columns = ["new1", "new2", "new3", "new4"]

In [68]:
df

new1  new2  new3  new4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [69]:
df.values

array([[35, 45, 33, 38],
       [23, 43, 11, 20],
       [44, 45, 36, 30],
       [20, 32, 17, 19],
       [44, 15, 43, 28],
       [30, 37, 23, 17]])

In [70]:
type(df.values)

numpy.ndarray

In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.shape

(6, 4)

In [73]:
df.ndim

2

In [74]:
df.size

24

## Element Selection Operations in Pandas DataFrames: Lesson 1

In [75]:
import numpy as np
import pandas as pd

In [76]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [77]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = ["v1 v2 v3 v4 v5".split()])

In [78]:
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [79]:
df.v1

v1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [80]:
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [81]:
df["VAL1"]

KeyError: 'VAL1'

In [ ]:
df.VAL1

In [ ]:
df["VAL1"].values

In [ ]:
df[["VAL1"]]

In [ ]:
df[["VAL1"]]["B":"D"]

In [ ]:
df[["VAL1"]][1:4]

## Element Selection Operations in Pandas DataFrames: Lesson 2

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df[["VAL2", "VAL5"]]

In [ ]:
variable = ["VAL3", "VAL4"]

In [ ]:
df[variable]

In [ ]:
df

In [ ]:
df["B":"D"]

In [ ]:
df[1:4]

In [ ]:
df["E"]

In [ ]:
df["E":"E"]

In [ ]:
df["E":"E"][["VAL2","VAL5"]]

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df.loc["A":"D"]

In [ ]:
df.iloc[0:4]

In [ ]:
df

In [ ]:
df.loc["C", "VAL4"]

In [ ]:
df.iloc[2, 3]

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 2

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df.loc["C":"G","VAL3"]

In [ ]:
df.loc["C":"G",["VAL3"]]

In [ ]:
df.loc["C":"G"][["VAL3"]]

In [ ]:
df

In [ ]:
df.iloc[2:7,2]

In [ ]:
df.iloc[2:7,[2]]

In [ ]:
df.iloc[2:7][["VAL3"]]

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 3

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df.loc["C":"H","VAL2":"VAL4"]

In [ ]:
df.iloc[2:8,1:4]

In [82]:
df.iloc[2:8,1:4].loc["E":"F", ["VAL3"]]

KeyError: "['VAL3'] not in index"

## Element Selection with Conditional Operations in Pandas Data Frames

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df > 20

In [ ]:
df[df > 20]

In [ ]:
df["VAL1"] < 20

In [ ]:
df[df["VAL1"] < 20]

In [83]:
df[df["VAL1"] < 20]["VAL2"]

KeyError: 'VAL1'

In [ ]:
df[df["VAL1"] < 20][["VAL2"]]

In [ ]:
df[df["VAL1"] > 20][["VAL2", "VAL5"]]

In [84]:
df 

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [85]:
df[(df["VAL1"] > 20) & (df["VAL4"] < 18)]

KeyError: 'VAL1'

In [ ]:
df[(df < 35) | (df["VAL5"] > 20)]

In [ ]:
df

In [86]:
df.loc[df.VAL2 > 25, ["VAL2", "VAL3", "VAL5"]]

AttributeError: 'DataFrame' object has no attribute 'VAL2'

## Adding Columns to Pandas Data Frames

In [87]:
import numpy as np
import pandas as pd

In [88]:
x = np.arange(0, 28).reshape(7, 4)

In [89]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [90]:
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [91]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [92]:
df["VAL1"] + df["VAL2"]

0     1
1     9
2    17
3    25
4    33
5    41
6    49
dtype: int32

In [93]:
df["VAL5"] = df["VAL1"] + df["VAL2"]

In [94]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
0     0     1     2     3     1
1     4     5     6     7     9
2     8     9    10    11    17
3    12    13    14    15    25
4    16    17    18    19    33
5    20    21    22    23    41
6    24    25    26    27    49

In [95]:
df["VAL6"] = df["VAL3"] * df["VAL4"]

In [96]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6
0     0     1     2     3     1     6
1     4     5     6     7     9    42
2     8     9    10    11    17   110
3    12    13    14    15    25   210
4    16    17    18    19    33   342
5    20    21    22    23    41   506
6    24    25    26    27    49   702

In [97]:
np.arange(28, 35)

array([28, 29, 30, 31, 32, 33, 34])

In [98]:
df["VAL7"] = np.arange(28, 35)

In [99]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7
0     0     1     2     3     1     6    28
1     4     5     6     7     9    42    29
2     8     9    10    11    17   110    30
3    12    13    14    15    25   210    31
4    16    17    18    19    33   342    32
5    20    21    22    23    41   506    33
6    24    25    26    27    49   702    34

In [100]:
df["VAL8"] = [35, 36, 37, 38, 39, 40, 41]

In [101]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7  VAL8
0     0     1     2     3     1     6    28    35
1     4     5     6     7     9    42    29    36
2     8     9    10    11    17   110    30    37
3    12    13    14    15    25   210    31    38
4    16    17    18    19    33   342    32    39
5    20    21    22    23    41   506    33    40
6    24    25    26    27    49   702    34    41

In [102]:
df["VAL9"] =[35, 36, 37, 38, 39, 40]

ValueError: Length of values (6) does not match length of index (7)

## Removing Rows and Columns from Pandas Data frames

In [103]:
import numpy as np
import pandas as pd

In [104]:
x = np.arange(0, 28).reshape(7, 4)
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [105]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [106]:
df.drop(["VAL3", "VAL4"], axis = 1)

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

In [107]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [108]:
df.drop(["VAL3", "VAL4"], axis = 1, inplace = True)

In [109]:
df

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

In [110]:
df

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

## Null Values in Pandas Dataframes

In [111]:
import pandas as pd
import numpy as np

In [112]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [113]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [114]:
df.isnull()

VAL1   VAL2   VAL3
0  False  False  False
1  False   True  False
2   True  False  False
3  False   True  False
4   True  False  False
5  False  False  False
6  False  False  False

In [115]:
df.isnull().sum()

VAL1    2
VAL2    2
VAL3    0
dtype: int64

In [116]:
len(df)

7

In [117]:
df.isnull().sum() / len(df) * 100

VAL1    28.571429
VAL2    28.571429
VAL3     0.000000
dtype: float64

In [118]:
df.notnull()

VAL1   VAL2  VAL3
0   True   True  True
1   True  False  True
2  False   True  True
3   True  False  True
4  False   True  True
5   True   True  True
6   True   True  True

In [119]:
df.notnull().sum()

VAL1    5
VAL2    5
VAL3    7
dtype: int64

In [120]:
df.notnull().sum().sum()

17

In [121]:
df["VAL1"].notnull()

0     True
1     True
2    False
3     True
4    False
5     True
6     True
Name: VAL1, dtype: bool

In [122]:
df[df["VAL1"].notnull()]

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
3   6.0    NaN   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [123]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [124]:
df.isnull().any()

VAL1     True
VAL2     True
VAL3    False
dtype: bool

In [125]:
df.isnull().any(axis = 1)

0    False
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [126]:
condition = df.isnull().any(axis = 1)

In [127]:
df[condition]

VAL1   VAL2    VAL3
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden

In [128]:
df[~condition]

VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [129]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [130]:
df.notnull().all()

VAL1    False
VAL2    False
VAL3     True
dtype: bool

In [131]:
df.isnull().all(axis = 1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

## Dropping Null Values: Dropna() Function

In [132]:
import pandas as pd
import numpy as np

In [133]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [134]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [135]:
df.dropna()

VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [136]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [137]:
df.dropna(axis = 1)

VAL3
0  France
1  Greece
2     USA
3   Japan
4  Sweden
5  Norway
6  Turkey

In [138]:
df["VAL4"] = np.nan

In [139]:
df

VAL1   VAL2    VAL3  VAL4
0   2.0  123.0  France   NaN
1   4.0    NaN  Greece   NaN
2   NaN  456.0     USA   NaN
3   6.0    NaN   Japan   NaN
4   NaN  789.0  Sweden   NaN
5   8.0  246.0  Norway   NaN
6  10.0  357.0  Turkey   NaN

In [140]:
df.dropna(how = "all")

VAL1   VAL2    VAL3  VAL4
0   2.0  123.0  France   NaN
1   4.0    NaN  Greece   NaN
2   NaN  456.0     USA   NaN
3   6.0    NaN   Japan   NaN
4   NaN  789.0  Sweden   NaN
5   8.0  246.0  Norway   NaN
6  10.0  357.0  Turkey   NaN

In [141]:
df.dropna(how = "all", axis = 1)

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [142]:
df

VAL1   VAL2    VAL3  VAL4
0   2.0  123.0  France   NaN
1   4.0    NaN  Greece   NaN
2   NaN  456.0     USA   NaN
3   6.0    NaN   Japan   NaN
4   NaN  789.0  Sweden   NaN
5   8.0  246.0  Norway   NaN
6  10.0  357.0  Turkey   NaN

In [143]:
df.dropna(how = "all", axis = 1, inplace = True)

In [144]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

## Filling Null Values: Fillna() Function

In [145]:
import pandas as pd
import numpy as np

In [146]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [147]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [148]:
df.fillna(100000)

VAL1      VAL2    VAL3
0       2.0     123.0  France
1       4.0  100000.0  Greece
2  100000.0     456.0     USA
3       6.0  100000.0   Japan
4  100000.0     789.0  Sweden
5       8.0     246.0  Norway
6      10.0     357.0  Turkey

In [149]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [150]:
df["VAL1"].fillna(100000)

0         2.0
1         4.0
2    100000.0
3         6.0
4    100000.0
5         8.0
6        10.0
Name: VAL1, dtype: float64

In [151]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [152]:
df.mean()

TypeError: Could not convert ['FranceGreeceUSAJapanSwedenNorwayTurkey'] to numeric

In [153]:
df.fillna(df.mean())

TypeError: Could not convert ['FranceGreeceUSAJapanSwedenNorwayTurkey'] to numeric

In [154]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [155]:
df.fillna({"VAL1":100000, "VAL2":200000})

VAL1      VAL2    VAL3
0       2.0     123.0  France
1       4.0  200000.0  Greece
2  100000.0     456.0     USA
3       6.0  200000.0   Japan
4  100000.0     789.0  Sweden
5       8.0     246.0  Norway
6      10.0     357.0  Turkey

In [156]:
df["VAL1"].fillna(df["VAL2"].mean())

0      2.0
1      4.0
2    394.2
3      6.0
4    394.2
5      8.0
6     10.0
Name: VAL1, dtype: float64

In [157]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [158]:
df["VAL3"][0::2]

0    France
2       USA
4    Sweden
6    Turkey
Name: VAL3, dtype: object

In [159]:
df["VAL3"][0::2] = np.nan

C:\Users\lenovo\AppData\Local\Temp\ipykernel_7784\12626872.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["VAL3"][0::2] = np.nan


In [160]:
df

VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0    NaN  Greece
2   NaN  456.0     NaN
3   6.0    NaN   Japan
4   NaN  789.0     NaN
5   8.0  246.0  Norway
6  10.0  357.0     NaN

In [161]:
df["VAL3"].fillna("Turkey")

0    Turkey
1    Greece
2    Turkey
3     Japan
4    Turkey
5    Norway
6    Turkey
Name: VAL3, dtype: object

In [162]:
df.fillna(method = "ffill")

VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0  123.0  Greece
2   4.0  456.0  Greece
3   6.0  456.0   Japan
4   6.0  789.0   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Norway

In [163]:
df.fillna(method = "pad")

VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0  123.0  Greece
2   4.0  456.0  Greece
3   6.0  456.0   Japan
4   6.0  789.0   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Norway

In [164]:
df.fillna(method = "bfill")

VAL1   VAL2    VAL3
0   2.0  123.0  Greece
1   4.0  456.0  Greece
2   6.0  456.0   Japan
3   6.0  789.0   Japan
4   8.0  789.0  Norway
5   8.0  246.0  Norway
6  10.0  357.0     NaN

In [165]:
df.fillna(method = "backfill")

VAL1   VAL2    VAL3
0   2.0  123.0  Greece
1   4.0  456.0  Greece
2   6.0  456.0   Japan
3   6.0  789.0   Japan
4   8.0  789.0  Norway
5   8.0  246.0  Norway
6  10.0  357.0     NaN