## Creating a Pandas Series with a List

In [1]:
import pandas as pd

In [2]:
pd.Series([10, 20, 30, 40, 50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
list_data = [2, 4, 6, 8, 10]
list_index = ["a", "b", "c", "d", "e"]

In [4]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

In [5]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [6]:
type(variable)

pandas.core.series.Series

In [7]:
list_data = [2, 4, 6, 8, 10, 12]
list_index = ["a", "b", "c", "d", "e"]

In [8]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

ValueError: Length of values (6) does not match length of index (5)

## Creating a Pandas Series with a Dictionary

In [ ]:
import pandas as pd 

In [ ]:
dictionary = {"ferrari" : 334.7, "porche" : 337.9, "lamborghini" : 349}

In [ ]:
pd.Series(data = dictionary)

In [ ]:
variable = pd.Series(data = dictionary, index = ["porche", "bugatti", "ferrari"])

In [ ]:
variable

## Creating Pandas Series with NumPy Array

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
example = np.array([1, 3.3, 5, 7.2, 9])
labels = np.array(["a", "b", "c", "d", "e"])

In [ ]:
variable = pd.Series(data = example, index = labels)

In [ ]:
variable

## Object Types in Series

In [ ]:
import pandas as pd

In [ ]:
pd.Series(["world", 100, 5.8, False])

In [ ]:
example = pd.Series(["world", 100, 5.8, False])

In [ ]:
example[0]

In [ ]:
print(type(example[0]))

In [ ]:
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

In [ ]:
pd.Series([sum, type, max])

## Examining the Primary Features of the Pandas Series  

In [ ]:
import pandas as pd

In [ ]:
example = pd.Series([10, 20, 30, 40, 50, 60, 70])

In [ ]:
example

In [ ]:
example.axes

In [9]:
example.dtype

NameError: name 'example' is not defined

In [10]:
example.size

NameError: name 'example' is not defined

In [11]:
example.ndim

NameError: name 'example' is not defined

In [12]:
example.head()

NameError: name 'example' is not defined

In [13]:
example.tail()

NameError: name 'example' is not defined

## Most Applied Methods on Pandas Series

In [14]:
import pandas as pd

In [15]:
variable = pd.Series([8, 3, 6, 5, 1], index = ["b", "d", "c", "a", "e"])

In [16]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [17]:
new_variable = variable.sort_index()

In [18]:
new_variable

a    5
b    8
c    6
d    3
e    1
dtype: int64

In [19]:
new_variable2 = variable.sort_values()

In [20]:
new_variable2

e    1
d    3
a    5
c    6
b    8
dtype: int64

In [21]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [22]:
variable.isin([6, 1])

b    False
d    False
c     True
a    False
e     True
dtype: bool

In [23]:
variable[variable.isin([6, 1])]

c    6
e    1
dtype: int64

In [24]:
variable.values

array([8, 3, 6, 5, 1], dtype=int64)

In [25]:
[i for i in variable.values]

[8, 3, 6, 5, 1]

In [26]:
variable.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [27]:
[i for i in variable.index]

['b', 'd', 'c', 'a', 'e']

In [28]:
variable.items

<bound method Series.items of b    8
d    3
c    6
a    5
e    1
dtype: int64>

In [29]:
variable.items()

In [30]:
list(variable.items())

[('b', 8), ('d', 3), ('c', 6), ('a', 5), ('e', 1)]

In [31]:
for index, value in variable.items():
    print(index, "-", value)

b - 8
d - 3
c - 6
a - 5
e - 1


## Indexing and Slicing Pandas Series

In [32]:
import pandas as pd

In [33]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [34]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [35]:
example["Germany"]

'+49'

In [36]:
example[1]

'+49'

In [37]:
example["France":"Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [38]:
example[2:5]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [39]:
example[2:5:2]

France    +33
Sweden    +46
dtype: object

In [40]:
example[["Norway", "Turkey"]]

Norway    +47
Turkey    +90
dtype: object

## Creating Pandas DataFrame with List

In [41]:
import pandas as pd

In [42]:
list_example = [5, 10, 15, 20, 25]

In [43]:
list_example

[5, 10, 15, 20, 25]

In [44]:
pd.DataFrame(data = list_example, columns = ["values"], dtype = "float" )

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

## Creating Pandas DataFrame with NumPy Array

In [45]:
import numpy as np
import pandas as pd

In [46]:
array_example = np.random.randint(0, 50, (4, 4))

In [47]:
array_example

array([[ 8, 49, 11, 30],
       [24, 24, 20,  3],
       [ 2, 16, 21, 33],
       [ 2,  8, 43, 20]])

In [48]:
df = pd.DataFrame(array_example, index = ["a", "b", "c", "d"], columns = ["val1", "val2", "val3", "val4"])

In [49]:
df

val1  val2  val3  val4
a     8    49    11    30
b    24    24    20     3
c     2    16    21    33
d     2     8    43    20

## Creating Pandas DataFrame with Dictionary

In [50]:
import numpy as np
import pandas as pd

In [51]:
x = np.random.randint(10, 50, size = 6)

In [52]:
x

array([19, 47, 48, 24, 26, 30])

In [53]:
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

In [54]:
dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

In [55]:
dict_example

{'val1': array([19, 47, 48, 24, 26, 30]),
 'val2': array([39, 46, 16, 43, 35, 13]),
 'val3': array([18, 49, 31, 45, 19, 37]),
 'val4': array([17, 27, 49, 42, 44, 32])}

In [56]:
df = pd.DataFrame(dict_example)

In [57]:
df

val1  val2  val3  val4
0    19    39    18    17
1    47    46    49    27
2    48    16    31    49
3    24    43    45    42
4    26    35    19    44
5    30    13    37    32

## Examining the Properties of Pandas DataFrames

In [58]:
import numpy as np
import pandas as pd

In [59]:
x = np.random.randint(10, 50, size = 6)
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

df = pd.DataFrame(dict_example)

In [60]:
df

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [61]:
df.head()

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28

In [62]:
df.head(3)

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30

In [63]:
df.tail(3)

val1  val2  val3  val4
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [64]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [65]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [66]:
df

val1  val2  val3  val4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [67]:
df.columns = ["new1", "new2", "new3", "new4"]

In [68]:
df

new1  new2  new3  new4
0    35    45    33    38
1    23    43    11    20
2    44    45    36    30
3    20    32    17    19
4    44    15    43    28
5    30    37    23    17

In [69]:
df.values

array([[35, 45, 33, 38],
       [23, 43, 11, 20],
       [44, 45, 36, 30],
       [20, 32, 17, 19],
       [44, 15, 43, 28],
       [30, 37, 23, 17]])

In [70]:
type(df.values)

numpy.ndarray

In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.shape

(6, 4)

In [73]:
df.ndim

2

In [74]:
df.size

24

## Element Selection Operations in Pandas DataFrames: Lesson 1

In [1]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = ["v1 v2 v3 v4 v5".split()])

In [4]:
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [5]:
df.v1

v1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [10]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [13]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [14]:
df["VAL1"]

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [15]:
df.VAL1

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [16]:
df["VAL1"].values

array([ 2.70684984, -0.31931804,  0.52881349,  0.95505651,  0.30266545,
        0.39052784])

In [17]:
df[["VAL1"]]

VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [18]:
df[["VAL1"]]["B":"D"]

VAL1
B -0.319318
C  0.528813
D  0.955057

In [19]:
df[["VAL1"]][1:4]

VAL1
B -0.319318
C  0.528813
D  0.955057

## Element Selection Operations in Pandas DataFrames: Lesson 2

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [ ]:
df

In [ ]:
df[["VAL2", "VAL5"]]

In [ ]:
variable = ["VAL3", "VAL4"]

In [ ]:
df[variable]

In [ ]:
df

In [ ]:
df["B":"D"]

In [ ]:
df[1:4]

In [ ]:
df["E"]

In [ ]:
df["E":"E"]

In [ ]:
df["E":"E"][["VAL2","VAL5"]]

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 1

In [20]:
import numpy as np
import pandas as pd

In [21]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [22]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [23]:
df.loc["A":"D"]

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [24]:
df.iloc[0:4]

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [25]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [26]:
df.loc["C", "VAL4"]

39

In [27]:
df.iloc[2, 3]

39

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 2

In [28]:
import numpy as np
import pandas as pd

In [29]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [30]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [32]:
df.loc["C":"G", ["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [33]:
df.loc["C":"G"][["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [34]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [35]:
df.iloc[2:7, 2]

C    22
D    44
E    41
F    46
G    20
Name: VAL3, dtype: int32

In [36]:
df.iloc[2:7, [2]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [37]:
df.iloc[2:7][["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 3

In [38]:
import numpy as np
import pandas as pd

In [39]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [40]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [41]:
df.loc["C":"H", "VAL2":"VAL4"]

VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [43]:
df.iloc[2:8, 1:4]

VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [45]:
df.iloc[2:8, 1:4].loc["E":"F", ["VAL3"]]

VAL3
E    41
F    46

## Element Selection with Conditional Operations in Pandas Data Frames

In [46]:
import numpy as np
import pandas as pd

In [47]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [48]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [49]:
df > 20

VAL1   VAL2   VAL3   VAL4   VAL5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True
I  False   True   True   True   True
J   True   True   True   True   True

In [50]:
df[df > 20]

VAL1  VAL2  VAL3  VAL4  VAL5
A  41.0  21.0  27.0   NaN  33.0
B  21.0   NaN  23.0   NaN  38.0
C   NaN   NaN  22.0  39.0  29.0
D   NaN  39.0  44.0   NaN  29.0
E   NaN  22.0  41.0  33.0   NaN
F   NaN   NaN  46.0  29.0  45.0
G  38.0   NaN   NaN  49.0  48.0
H   NaN  28.0   NaN  49.0  25.0
I   NaN  22.0  27.0  21.0  25.0
J  43.0  39.0  34.0  46.0  29.0

In [52]:
df["VAL1"] < 20

A    False
B    False
C     True
D     True
E    False
F     True
G    False
H     True
I     True
J    False
Name: VAL1, dtype: bool

In [53]:
df[df["VAL1"] < 20]

VAL1  VAL2  VAL3  VAL4  VAL5
C    10    15    22    39    29
D    18    39    44    18    29
F    19    18    46    29    45
H    19    28    17    49    25
I    10    22    27    21    25

In [54]:
df[df["VAL1"] < 20]["VAL2"]

C    15
D    39
F    18
H    28
I    22
Name: VAL2, dtype: int32

In [55]:
df[df["VAL1"] < 20][["VAL2"]]

VAL2
C    15
D    39
F    18
H    28
I    22

In [60]:
df[df["VAL1"] < 20][["VAL2","VAL5"]]

VAL2  VAL5
C    15    29
D    39    29
F    18    45
H    28    25
I    22    25

In [61]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [62]:
df[(df["VAL1"] > 20) & (df["VAL4"] > 18)]

VAL1  VAL2  VAL3  VAL4  VAL5
G    38    17    20    49    48
J    43    39    34    46    29

In [63]:
df[(df < 35) | (df["VAL5"] > 20)]

VAL1  VAL2  VAL3  VAL4  VAL5
A   NaN  21.0  27.0  16.0  33.0
B  21.0  19.0  23.0  14.0   NaN
C  10.0  15.0  22.0   NaN  29.0
D  18.0   NaN   NaN  18.0  29.0
E  20.0  22.0   NaN  33.0  10.0
F  19.0  18.0   NaN  29.0   NaN
G   NaN  17.0  20.0   NaN   NaN
H  19.0  28.0  17.0   NaN  25.0
I  10.0  22.0  27.0  21.0  25.0
J   NaN   NaN  34.0   NaN  29.0

In [65]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [66]:
df.loc[df.VAL2 > 25, ["VAL2", "VAL3", "VAL5"]]

VAL2  VAL3  VAL5
D    39    44    29
H    28    17    25
J    39    34    29

## Adding Columns to Pandas Data Frames

In [67]:
import numpy as np
import pandas as pd

In [68]:
x = np.arange(0, 28).reshape(7, 4)

In [69]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [70]:
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [71]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [72]:
df["VAL1"] + df["VAL2"]

0     1
1     9
2    17
3    25
4    33
5    41
6    49
dtype: int32

In [73]:
df["VAL5"] = df["VAL1"] + df["VAL2"]

In [74]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
0     0     1     2     3     1
1     4     5     6     7     9
2     8     9    10    11    17
3    12    13    14    15    25
4    16    17    18    19    33
5    20    21    22    23    41
6    24    25    26    27    49

In [75]:
df["VAL6"] = df["VAL3"] * df["VAL4"]

In [76]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6
0     0     1     2     3     1     6
1     4     5     6     7     9    42
2     8     9    10    11    17   110
3    12    13    14    15    25   210
4    16    17    18    19    33   342
5    20    21    22    23    41   506
6    24    25    26    27    49   702

In [77]:
np.arange(28, 35)

array([28, 29, 30, 31, 32, 33, 34])

In [78]:
df["VAL7"] = np.arange(28, 35)

In [79]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7
0     0     1     2     3     1     6    28
1     4     5     6     7     9    42    29
2     8     9    10    11    17   110    30
3    12    13    14    15    25   210    31
4    16    17    18    19    33   342    32
5    20    21    22    23    41   506    33
6    24    25    26    27    49   702    34

In [80]:
df["VAL8"] = [35, 36, 37, 38, 39, 40, 41]

In [81]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7  VAL8
0     0     1     2     3     1     6    28    35
1     4     5     6     7     9    42    29    36
2     8     9    10    11    17   110    30    37
3    12    13    14    15    25   210    31    38
4    16    17    18    19    33   342    32    39
5    20    21    22    23    41   506    33    40
6    24    25    26    27    49   702    34    41

In [82]:
df["VAL9"] = [35, 36, 37, 38, 39, 40]

ValueError: Length of values (6) does not match length of index (7)

## Removing Rows and Columns from Pandas Data frames

In [83]:
import numpy as np
import pandas as pd

In [84]:
x = np.arange(0, 28).reshape(7, 4)
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [85]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [87]:
df.drop(["VAL3", "VAL4"], axis = 1)

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

In [89]:
df.drop(["VAL3", "VAL4"], axis = 1, inplace = True)

In [90]:
df

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

## Null Values in Pandas Dataframes

In [92]:
import pandas as pd
import numpy as np

In [93]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [94]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [96]:
df.isnull()

VAL1   VAL2   VAL3
0  False  False  False
1  False   True  False
2   True  False  False
3  False   True  False
4   True  False  False
5  False  False  False
6  False  False  False

In [97]:
df.isnull().sum()

VAL1    2
VAL2    2
VAL3    0
dtype: int64

In [98]:
len(df)

7

In [99]:
df.isnull().sum() / len(df) * 100

VAL1    28.571429
VAL2    28.571429
VAL3     0.000000
dtype: float64

In [100]:
df.notnull()

VAL1   VAL2  VAL3
0   True   True  True
1   True  False  True
2  False   True  True
3   True  False  True
4  False   True  True
5   True   True  True
6   True   True  True

In [101]:
df.notnull().sum()

VAL1    5
VAL2    5
VAL3    7
dtype: int64

In [102]:
df.notnull().sum().sum()

17

In [103]:
df["VAL1"].notnull()

0     True
1     True
2    False
3     True
4    False
5     True
6     True
Name: VAL1, dtype: bool

In [105]:
df[df["VAL1"].notnull()]

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
3   6.0    NaN   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [106]:
df.isnull().any()

VAL1     True
VAL2     True
VAL3    False
dtype: bool

In [107]:
df.isnull().any(axis=1)

0    False
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [110]:
condition = df.isnull().any(axis=1)

In [111]:
df[condition]

VAL1   VAL2    VAL3
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden

In [114]:
df[-condition]

VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [115]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [116]:
df.notnull().all()

VAL1    False
VAL2    False
VAL3     True
dtype: bool

In [117]:
df.notnull().all(axis=1)

0     True
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

## Dropping Null Values: Dropna() Function

In [118]:
import pandas as pd
import numpy as np

In [119]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [120]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [121]:
df.dropna()

VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [123]:
df.dropna(axis=1)

VAL3
0  France
1  Greece
2     USA
3   Japan
4  Sweden
5  Norway
6  Turkey

In [125]:
df["VAL4"] = np.nan

In [126]:
df

VAL1   VAL2    VAL3  VAL4
0   2.0  123.0  France   NaN
1   4.0    NaN  Greece   NaN
2   NaN  456.0     USA   NaN
3   6.0    NaN   Japan   NaN
4   NaN  789.0  Sweden   NaN
5   8.0  246.0  Norway   NaN
6  10.0  357.0  Turkey   NaN

In [127]:
df.dropna(how="all")

VAL1   VAL2    VAL3  VAL4
0   2.0  123.0  France   NaN
1   4.0    NaN  Greece   NaN
2   NaN  456.0     USA   NaN
3   6.0    NaN   Japan   NaN
4   NaN  789.0  Sweden   NaN
5   8.0  246.0  Norway   NaN
6  10.0  357.0  Turkey   NaN

In [128]:
df.dropna(how="all", axis=1)

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [129]:
df.dropna(how="all", axis=1, inplace=True)

In [130]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

## Filling Null Values: Fillna() Function

In [150]:
import pandas as pd
import numpy as np

In [151]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [152]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [153]:
df.fillna(1000000)

VAL1       VAL2    VAL3
0        2.0      123.0  France
1        4.0  1000000.0  Greece
2  1000000.0      456.0     USA
3        6.0  1000000.0   Japan
4  1000000.0      789.0  Sweden
5        8.0      246.0  Norway
6       10.0      357.0  Turkey

In [154]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [155]:
df["VAL1"].fillna(1000000)

0          2.0
1          4.0
2    1000000.0
3          6.0
4    1000000.0
5          8.0
6         10.0
Name: VAL1, dtype: float64

In [156]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [157]:
df.VAL1.mean()

6.0

In [158]:
df.fillna({"VAL1": 200000, "VAL2": 1000000})

VAL1       VAL2    VAL3
0       2.0      123.0  France
1       4.0  1000000.0  Greece
2  200000.0      456.0     USA
3       6.0  1000000.0   Japan
4  200000.0      789.0  Sweden
5       8.0      246.0  Norway
6      10.0      357.0  Turkey

In [159]:
df.fillna({"VAL1": df.VAL1.mean(), "VAL2": df.VAL2.mean()})

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0  394.2  Greece
2   6.0  456.0     USA
3   6.0  394.2   Japan
4   6.0  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [160]:
df["VAL1"].fillna(df["VAL1"].mean())

0     2.0
1     4.0
2     6.0
3     6.0
4     6.0
5     8.0
6    10.0
Name: VAL1, dtype: float64

In [161]:
df["VAL3"][0::2]

0    France
2       USA
4    Sweden
6    Turkey
Name: VAL3, dtype: object

In [162]:
df["VAL3"][0::2] = np.nan

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15764\12626872.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["VAL3"][0::2] = np.nan


In [163]:
df

VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0    NaN  Greece
2   NaN  456.0     NaN
3   6.0    NaN   Japan
4   NaN  789.0     NaN
5   8.0  246.0  Norway
6  10.0  357.0     NaN

In [164]:
df["VAL3"].fillna("Turkey")

0    Turkey
1    Greece
2    Turkey
3     Japan
4    Turkey
5    Norway
6    Turkey
Name: VAL3, dtype: object

In [165]:
df

VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0    NaN  Greece
2   NaN  456.0     NaN
3   6.0    NaN   Japan
4   NaN  789.0     NaN
5   8.0  246.0  Norway
6  10.0  357.0     NaN

In [166]:
df.fillna(method = "ffill")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15764\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")


VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0  123.0  Greece
2   4.0  456.0  Greece
3   6.0  456.0   Japan
4   6.0  789.0   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Norway

In [167]:
df.describe()

VAL1        VAL2
count   5.000000    5.000000
mean    6.000000  394.200000
std     3.162278  253.270014
min     2.000000  123.000000
25%     4.000000  246.000000
50%     6.000000  357.000000
75%     8.000000  456.000000
max    10.000000  789.000000