# The Power of NumPY

In [1]:
range(0, 5)

range(0, 5)

In [2]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0, 5, 2))

[0, 2, 4]

In [4]:
list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]

In [5]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
new_list = []

for i in range(0, len(list1)):
    x = list1[i] * list2[i]
    new_list.append(x)
    
print(new_list)

[2, 12, 30, 56, 90]


In [7]:
import numpy as np

In [8]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([2, 4, 6, 8, 10])

In [9]:
print(type(x))

<class 'numpy.ndarray'>


In [10]:
x * y

array([ 2, 12, 30, 56, 90])

# Creating NumPy Array with the Array() Method

In [11]:
import numpy as np

In [12]:
np.array([2, 4, 6, 8])

array([2, 4, 6, 8])

In [13]:
variable = [5.8, 9, 7, 5]

In [14]:
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [15]:
new_variable = np.array([5.8, 9, 7, 5])

In [16]:
print(type(new_variable[0]))
print(type(new_variable[1]))

<class 'numpy.float64'>
<class 'numpy.float64'>


In [17]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [18]:
new_variable2 = np.array([5.8, 9, 7, 5], dtype = "int")

In [19]:
new_variable2

array([5, 9, 7, 5])

# Creating NumPy Array with the Zeros() Method

In [20]:
import numpy as np

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Creating NumPy Array with the Ones() Method

In [23]:
import numpy as np

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((3, 4, 5), dtype = "int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

# Creating NumPy Array with the Full() Method

In [26]:
import numpy as np

In [27]:
np.full(8, 5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [28]:
np.full((2, 3), 6, dtype = "float")

array([[6., 6., 6.],
       [6., 6., 6.]])

# Creating NumPy Array with the Arange() Method

In [29]:
import numpy as np

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
example = np.arange(3, 10, dtype = "float")

In [32]:
print(example)

[3. 4. 5. 6. 7. 8. 9.]


In [33]:
example

array([3., 4., 5., 6., 7., 8., 9.])

# Creating NumPy Array with the Eye() Method

In [34]:
import numpy as np

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
np.eye(3, 2, dtype = "bool")

array([[ True, False],
       [False,  True],
       [False, False]])

# Creating NumPy Array with the Linspace() Method

In [38]:
import numpy as np

In [39]:
np.linspace(10, 30, 10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

# Creating NumPy Array with the Random() Method

In [40]:
import numpy as np

In [41]:
# rand method
np.random.rand(5)

array([0.83581698, 0.36811102, 0.40562709, 0.03383633, 0.84538748])

In [42]:
np.random.rand(2, 3)

array([[0.38059774, 0.99355331, 0.71911894],
       [0.18989233, 0.32490133, 0.65526688]])

In [43]:
# random.normal method
np.random.normal(20, 5, (4, 3))

array([[20.05560919, 23.52275141, 15.34084506],
       [27.70272321, 18.2045317 , 12.30539254],
       [17.98201011, 22.83291014, 18.35153278],
       [19.52650954, 23.08748435, 17.44552048]])

In [44]:
# randint method
np.random.randint(0, 10, (4, 4))

array([[7, 3, 3, 3],
       [0, 6, 8, 6],
       [5, 5, 7, 1],
       [6, 4, 5, 5]])

# Properties of NumPy Array

In [45]:
import numpy as np

In [46]:
matrix = np.random.randint(10, 50, (5, 4))

In [47]:
matrix

array([[44, 21, 16, 42],
       [36, 19, 49, 16],
       [27, 16, 20, 31],
       [42, 39, 33, 43],
       [28, 23, 15, 29]])

In [48]:
matrix.ndim

2

In [49]:
matrix.shape

(5, 4)

In [50]:
matrix.size

20

In [51]:
matrix.dtype

dtype('int32')

# Reshaping a NumPy Array: Reshape() Method

In [52]:
import numpy as np

In [53]:
example = np.arange(1, 16)

In [54]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
array = example.reshape((3, 5))

In [56]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
example.ndim

1

In [58]:
array.ndim

2

In [59]:
example.reshape((4, 3))

ValueError: cannot reshape array of size 15 into shape (4,3)

# Identifying the Largest Element of a NumPy Array: max(), argmax() methods

In [60]:
import numpy as np

In [61]:
array = np.random.randint(0, 50, 10)
array

array([47, 25,  1, 10, 45, 31, 31, 27,  2,  9])

In [62]:
array.max()

47

In [63]:
array.argmax()

0

In [64]:
array2 = np.random.randint(0, 50, (4, 3))
array2

array([[ 4, 44, 30],
       [13,  7, 29],
       [15, 10, 49],
       [16, 19, 25]])

In [65]:
array2.max()

49

In [66]:
array2.argmax()

8

# Detecting Least Element of NumPy Array: min(), argmin() methods

In [67]:
array = np.random.randint(20, 70, 10)
array

array([47, 65, 52, 44, 32, 59, 51, 45, 39, 47])

In [68]:
array.min()

32

In [69]:
array.argmin()

4

In [70]:
array2 = np.random.randint(20, 70, (5,3))
array2

array([[52, 27, 58],
       [66, 45, 69],
       [60, 26, 43],
       [32, 46, 37],
       [45, 49, 41]])

In [71]:
array2.min()

26

In [72]:
array2.argmin()

7

# Concatenating NumPy Arrays: concatenate() method

In [73]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

In [74]:
np.concatenate([array1, array2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
array3 = np.arange(1, 7).reshape((2, 3))
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
array4 = np.array([[7, 8, 9], [10, 11, 12]])
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [77]:
np.concatenate([array3, array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
np.concatenate([array3, array4], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [79]:
np.concatenate([array1, array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [80]:
array5 = np.arange(1, 11). reshape(5, 2)
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [81]:
np.concatenate([array3, array5])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

# Splitting One-Dimensional NumPy Array: The split() method

In [82]:
array = np.array([1, 3, 5, 50, 50 , 2, 4, 6])
array

array([ 1,  3,  5, 50, 50,  2,  4,  6])

In [83]:
np.split(array, [3, 5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [84]:
x, y, z = np.split(array, [3, 5])

In [85]:
x

array([1, 3, 5])

In [86]:
y

array([50, 50])

In [87]:
z

array([2, 4, 6])

In [88]:
np.split(array, 4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [89]:
np.split(array, 5)

ValueError: array split does not result in an equal division

# Splitting Two-Dimensional NumPy Array: The split(), vsplit(), hsplit() method

In [ ]:
array = np.arange(20).reshape(5, 4)
array

In [90]:
np.split(array, [1, 3])

[array([1]), array([3, 5]), array([50, 50,  2,  4,  6])]

In [91]:
x, y, z = np.split(array, [1, 3])

In [92]:
x

array([1])

In [93]:
y

array([3, 5])

In [94]:
z

array([50, 50,  2,  4,  6])

In [95]:
np.split(array, [1, 3], axis = 1)

IndexError: tuple index out of range

In [ ]:
# hsplit()
array

In [96]:
np.hsplit(array, 4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [97]:
np.vsplit(array, 5)

ValueError: vsplit only works on arrays of 2 or more dimensions

# Sorting NumPy Arrays: sort() method

In [98]:
variable = np.array([3, 5, 1, 8, 6, 2, 9])
variable

array([3, 5, 1, 8, 6, 2, 9])

In [99]:
variable.sort()

In [100]:
np.sort(variable)

array([1, 2, 3, 5, 6, 8, 9])

In [101]:
example = np.random.normal(30, 10, (4,4))
example

array([[26.66940159, 22.20213865, 40.10830637, 28.51936905],
       [29.27511876, 40.67481977, 13.61790316, 30.34047156],
       [35.44551718, 33.39338813, 29.30576763, 30.48352279],
       [25.28241011, 10.57717825, 23.19454359, 26.46755496]])

In [102]:
np.sort(example)

array([[22.20213865, 26.66940159, 28.51936905, 40.10830637],
       [13.61790316, 29.27511876, 30.34047156, 40.67481977],
       [29.30576763, 30.48352279, 33.39338813, 35.44551718],
       [10.57717825, 23.19454359, 25.28241011, 26.46755496]])

In [103]:
np.sort(example, axis = 0)

array([[25.28241011, 10.57717825, 13.61790316, 26.46755496],
       [26.66940159, 22.20213865, 23.19454359, 28.51936905],
       [29.27511876, 33.39338813, 29.30576763, 30.34047156],
       [35.44551718, 40.67481977, 40.10830637, 30.48352279]])

# Indexing NumPy Arrays

In [104]:
array = np.arange(0, 11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
array[4]

4

In [106]:
array[-2]

9

In [107]:
variable = np.array([[5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]])
variable

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [108]:
variable[0, 0]

5

In [109]:
variable[2, 1]

40

In [110]:
variable[-1, -3]

35

# Slicing One-Dimensional NumPy Array

In [111]:
example = np.arange(10, 20)
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [112]:
example[2:6]

array([12, 13, 14, 15])

In [113]:
example[3::2]

array([13, 15, 17, 19])

In [114]:
example[:7:3]

array([10, 13, 16])

# Slicing Two-Dimensional NumPy Array

In [115]:
array = np.arange(30).reshape(6, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [116]:
array[2, :]

array([10, 11, 12, 13, 14])

In [117]:
array[2]

array([10, 11, 12, 13, 14])

In [118]:
array[0]

array([0, 1, 2, 3, 4])

In [119]:
array[:,2]

array([ 2,  7, 12, 17, 22, 27])

In [120]:
array[:,0]

array([ 0,  5, 10, 15, 20, 25])

In [121]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [122]:
array[1:4, 0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [123]:
array[0::2, 0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

# Assigining Value to One-Dimensional Array

In [1]:
import numpy as np

In [2]:
variable = np.array([0, 1, 2, 3, 7, 5, 6, 8, 9])
variable

array([0, 1, 2, 3, 7, 5, 6, 8, 9])

In [3]:
variable[4] = 4
variable

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [4]:
variable[7] = 7
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [6]:
variable[8] = 8
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
variable[0:5] = 10
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8])

In [8]:
variable[5:]

array([5, 6, 7, 8])

In [9]:
variable[5:] = 20, 30, 40, 50
variable

array([10, 10, 10, 10, 10, 20, 30, 40, 50])

# Assigining Value to Two-Dimensional Array

In [16]:
example = np.array([[10, 20 , 30],
                   [40, 50, 60],
                   [70, 80 ,90]])
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
example[1, 1] = 100
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [18]:
example[:, 2] = 100
example

array([[ 10,  20, 100],
       [ 40, 100, 100],
       [ 70,  80, 100]])

In [19]:
example[1, 0] = 100.6
example

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [20]:
example[0::2, 0:2]

array([[10, 20],
       [70, 80]])

In [21]:
example[0::2, 0:2] = 100
example

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [22]:
example[0]

array([100, 100, 100])

In [23]:
example[0] = 10, 20, 30
example

array([[ 10,  20,  30],
       [100, 100, 100],
       [100, 100, 100]])

# Fancy Indexing of One-Dimensional Array

In [25]:
fancy = np.arange(0, 50, 5)
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [26]:
fancy[1]

5

In [27]:
fancy[3]

15

In [28]:
fancy[5]

25

In [31]:
[fancy[1], fancy[3], fancy[5]]

[5, 15, 25]

In [34]:
indexs = [1, 3, 5]
fancy[indexs]

array([ 5, 15, 25])

In [35]:
array = np.array([1, 3, 4])
fancy[array]

array([ 5, 15, 20])

# Fancy Indexing of Two-Dimensional Array

In [37]:
variable = np.zeros((10, 10), dtype = "int")
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
variable.shape

(10, 10)

In [40]:
variable.shape[0]

10

In [41]:
row = variable.shape[0]

In [42]:
variable[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
for i in range(row):
    variable[i] = i
    
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [44]:
list1 = [1, 3, 5, 7]
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [45]:
list2 = [8, 5, 2, 7, 3]
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [46]:
example = np.arange(1, 17).reshape((4, 4))
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
example[[0, 3], [1, 2]]

array([ 2, 15])

In [48]:
row = [0, 2, 3, 1]
column = [3, 0, 2, 1]
example[row, column]

array([ 4,  9, 15,  6])

# Combining Fancy Index with Normal Indexing

In [49]:
example = np.arange(1, 17).reshape((4, 4))
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
example[1, [1, 3]]

array([6, 8])

In [51]:
example[[0, 3], 1]

array([ 2, 14])

# Combining Fancy Index with Normal Slicing

In [52]:
example = np.arange(1, 17).reshape((4, 4))
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
example[0:,[1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [54]:
example[1:3, [1, 2]]

array([[ 6,  7],
       [10, 11]])

# Operations with Comparision Operators

In [57]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [60]:
condition = array <= 4
array[condition]

array([1, 2, 3, 4])

In [61]:
new_condition = (array != 8) & (array >= 6)
array[new_condition]

array([ 6,  7,  9, 10])

# Arithmetic Operations in NumPy

In [62]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [64]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [65]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
((array * 10) + 20) / 5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [67]:
array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [68]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.subtract(array, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [70]:
np.multiply(array, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [71]:
np.add(array, 20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [72]:
np.divide(array, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [73]:
array ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [74]:
np.power(array, 3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [75]:
np.sqrt(4)

2.0

In [76]:
np.sqrt(100)

10.0

In [77]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [78]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [79]:
np.sin(180)

-0.8011526357338304

In [80]:
np.cos(180)

-0.5984600690578581

In [81]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [82]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

# Statistical Operations in NumPy

In [84]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.sum(array)

55

In [86]:
np.mean(array)

5.5

In [87]:
np.median(array)

5.5

In [88]:
np.min(array)

1

In [89]:
np.max(array)

10

In [90]:
np.std(array)

2.8722813232690143

In [91]:
np.var(array)

8.25

In [92]:
np.sqrt(np.var(array))

2.8722813232690143

# Solving Second-Degree Equations in NumPy

2x1 + x2 = 5

-3x1 + 6x2 = 0

In [93]:
coefficient = np.array([[2, 1], [-3, 6]])
coefficient

array([[ 2,  1],
       [-3,  6]])

In [95]:
output = np.array([5, 0])
output

array([5, 0])

In [96]:
np.linalg.solve(coefficient, output)

array([2., 1.])